### ISSUE TITLE
Маркдаун ссылка не отрендерилась в html

### ISSUE THREAD

**Issue by ArchieSW** [Insayt/nestjs.ru.com#5]
![image](https://user-images.githubusercontent.com/47922037/185759803-7019f6a3-df83-426f-a4ee-e0b0d8cdee07.png)
В секции Обзор/Контроллеры/Scopes в последнем абзаце прописана неправильная ссылка, которая в последствии не превратилась в < / a> тег.

**Comment by ArchieSW** [comment]
![image](https://user-images.githubusercontent.com/47922037/185759979-ea6eb2c3-db5d-49bf-b647-2ed3b9f581dc.png)
В Обзор/Контроллеры/Тело запроса также

**Comment by andrewgrow** [comment]
@ArchieSW Hi Dmitry, the Pull Request was created by your remarks. https://github.com/Insayt/nestjs.ru.com/pull/7
