### ISSUE TITLE
Недоступен сайт nestjs.ru.com

### ISSUE THREAD

**Issue by strukovd** [Insayt/nestjs.ru.com#9]
Уже пару дней недоступен сайт, что-то случилось?

**Comment by Insayt** [comment]
@strukovd привет. Да reg.ru запросил конских денег за продление домена - на днях постараюсь передеплоить на github-pages домен

**Comment by Insayt** [comment]
@strukovd пока можно сюда https://insayt.github.io/nestjs.ru.com/
